import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Practice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark text-white min-h-screen bg-gradient-to-br from-[#2c3e50] via-[#4b6cb7] to-[#182848]" >
        <nav className="backdrop-blur-md bg-white/5 border-b border-white/10 sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
            <div className="text-2xl font-bold tracking-wide">MyWebsite</div>
            <div className="space-x-6 hidden md:flex">
              {[
                { href: "/", label: "Home" },
                { href: "/about", label: "About" },
                { href: "/students", label: "Student" },
                { href: "/faculties", label: "Faculty" },
                { href: "/login", label: "Login" },
                { href: "/signup", label: "Signup" },
              ].map(({ href, label }) => (
                <Link
                  key={href}
                  href={href}
                  className="text-sm font-medium hover:text-cyan-300 transition duration-200"
                >
                  {label}
                </Link>
              ))}
            </div>
          </div>
        </nav>

        <main className="min-h-[calc(100vh-4rem)] flex items-center justify-center px-4 py-10">
          <div className="w-full max-w-5xl backdrop-blur-md bg-white/10 border border-white/20 rounded-2xl shadow-2xl p-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
